### ISSUE TITLE
As a developer, I want to parse information from the Yelp API so the data is usable. 2Hr

### ISSUE THREAD

**Issue by emily-yang** [project-aura/server#4]

**Comment by magicmitra** [comment]
We should probably move the fetcher function in the back end then? And coat it as a router or middleware like what Andrew did with the examples.

**Comment by ScotteRoberts** [comment]
If we are storing our data in the database, then it would be great as an API endpoint. 😄

**Comment by magicmitra** [comment]
Closing this due to the YELP API not being useful to our specs right now.

**Comment by magicmitra** [comment]
Closing this due to the YELP API not being useful to our specs right now.
